"""empty message

Revision ID: 86c8b77707ca
Revises: 9066005691ac
Create Date: 2022-05-10 09:38:13.128895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c8b77707ca'
down_revision = '9066005691ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
